region              = "us-west-2"
profile             = "john-default"
ssh_public_key_path = "~/.ssh/id_rsa.pub"
environment         = "tools"
stack               = "server"
network_cidr        = "10.0.0.0/16"
